UseMySQL: true
DatabaseAddress: "localhost"
DatabasePort: "3306"
DatabaseName: "discordbot"
DatabaseUser: "root"
DatabasePassword: ""
BotToken: "ENTER_YOUR_BOT_TOKEN_HERE"
GuildID: "ENTER_YOUR_GUILD_ID_HERE"
VerificationChannelID: "ENTER_YOUR_VERIFICATION_CHANNEL_ID_HERE"
DeleteMessageAfter: 10
VerificationExpireAfter: 120
LimitRolesToOne: true
ForceNicknamesOnDiscord: true
Prefix: "&#FF5555&lDiscordVerifier &#AA0000» &#FF5555"
AdminCommandUsage: "Available commands:\n&#FFFFFF/discord info <nick> &#FF5555- shows information about the player,\n&#FFFFFF/discord reload &#FF5555- reloads plugin."
PlayerNotVerified: "Player is not verified."
PlayerNotFound: "Player couldn't be found."
PlayerInfo: "Information about the player &#FFFFFF%VAR%&#FF5555:\n&#FF5555UUID: &#FFFFFF%VAR2%,\n&#FF5555Discord ID: &#FFFFFF%VAR3%,\n&#FF5555Discord Name: &#FFFFFF%VAR4%,\n&#FF5555Online: &#FFFFFF%VAR5%&#FF5555."
Online: "online"
Offline: "offline"
DiscordInfo: "Join our Discord server and get verified right now, if you haven't already: &#FFFFFFdiscord.gg/someserver&#FF5555."
PlayerNotFoundTitle: "Player with nickname %NICKNAME% couldn't be found on the server."
PlayerNotFoundBody: "You have to be on the server to get verified."
PlayerNotFoundFooter: ""
PlayerAlreadyVerifiedTitle: "Player with nickname %NICKNAME% is verified yet."
PlayerAlreadyVerifiedBody: "If you want to undo your verification, use /discord unlink command in game"
PlayerAlreadyVerifiedFooter: ""
DiscordAlreadyVerifiedTitle: "Your Discord account is linked to the verified player yet."
DiscordAlreadyVerifiedBody: "If you want to undo your verification, use /discord unlink command in game."
DiscordAlreadyVerifiedFooter: ""
VerificationAcceptedTitle: "Player %NICKNAME% has been found on the server."
VerificationAcceptedBody: "You have to accept the verification, typing /discord accept in game."
VerificationAcceptedFooter: ""
AcceptVerification: "You received verification request from Discord account &#FFFFFF%VAR%&#FF5555. To accept verification, type &#FFFFFF/discord accept&#FF5555, to deny it, type &#FFFFFF/discord deny&#FF5555."
VerificationExpired: "Verification request from Discord account &#FFFFFF%VAR% &#FF5555expired."
VerifiedSuccessfully: "Your Discord account has been verified and successfully linked with Discord account &#FFFFFF%VAR%&#FF5555."
VerificationDenied: "You denied verification request."
NoVerificationRequired: "You don't have any verification request."
VerificationSuccessfulTitle: "Verification was successful."
VerificationSuccessfulBody: "You are now verified."
VerificationSuccessfulFooter: ""
VerificationDeniedTitle: "Verification has been denied."
VerificationDeniedBody: "You cancelled the verification."
VerificationDeniedFooter: ""
NotVerified: "You are not verified."
UnverifiedSuccesfully: "Successfully unlinked your account, you are now not seen as verified."
ConfigReloaded: "Configuration has been reloaded."
NotVerifiedYet: "Join our Discord server and get verified right now: &#FFFFFFdiscord.gg/someserver&#FF5555."
Roles:
  admin: "111111111111111111"
  vip: "222222222222222222"
  default: "333333333333333333"