# Database settings.
data:
  # Set to 'SQLite' or 'MySQL'.
  database: "SQLite"
  # Change if you set database to the 'MySQL'.
  mysql:
    address: "localhost"
    port: "3306"
    database-name: "discordverifier"
    user: "root"
    password: ""
discord:
  # Set here your bot token. (more: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token)
  token: "ENTER_YOUR_BOT_TOKEN_HERE"
  # Set here your Discord server ID. (more: https://support.discord.com/hc/pl/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)
  guild-id: "ENTER_YOUR_GUILD_ID_HERE"
  # Set here your channel ID that will be used for verification commands. (more in the link above)
  channel-id: "ENTER_YOUR_CHANNEL_ID_HERE"
  # Delay in seconds after which each message sent in the verification channel will be deleted.
  delete-message-after: 20
  # Delay in seconds after which verification request will expire.
  verification-expire-time: 120
  # If true, when a player unlinks and they are still on the server, kick them from the proxy
  kick-on-unlink: false
  # If anything else but '', when a player unlinks and they are still on the server, send them to this server.
  # If the plugin can't find the server specified, it will kick the player if kick-on-unlink is true.
  send-to-server-on-unlink: ''
  # If set to true, only highest placed role (defined by player's permissions) will be assigned.
  one-role-limit: true
  # If a user has any of these roles, then they will be prevented from joining the server and unlinking accounts.
  banned-roles:
  #  - 111111111111111111
  sync:
    nickname:
      enable: false
      # If set to true, the nickname will be set on every player login
      # If false, the nickname will only be set when the player first verifies
      force: false
      # If true, set Minecraft name to Discord nickname.
      # If false, set Discord nickname to Minecraft name.
      discord-to-minecraft: true
      # If set to true, Discord user nickname will inherit the nickname based on the linked player account.
    group:
      # List of permissions with their corresponding roles' IDs.
      # permission groups -> Discord roles
      roles:
    #    admin: "111111111111111111" # If player has a permission group.admin and their account is verified, he will receive the role with ID 111111111111111111.
    #    vip: "222222222222222222"
    #    default: "333333333333333333"
      # Discord roles -> Luckperms groups
      groups:
    #    "111111111111111111": "admin"
    #    "222222222222222222": "rank:vip" # prefix rank: here means luckperms track (lp user <user> parent settrack <track(rank)> <group(vip)>
      # If a user's group is removed and is in a track, what group should be assigned to the user?
      track-default-groups:
    #    "trackName": "defaultGroup"
      # give these permissions when linked (also removes them when unlinked)
      verification-permissions:
        - "discordverifier.linked"
    #    - "group.discordlinked"
# All available messages which players and Discord users can see.
# Available formats:
# &#{HEX}{MESSAGE} - Text colored in one color.
# &#gr{HEX1}{HEX2}{MESSAGE} - Text colored with a gradient of two colors.
messages:
  kick:
    unlink: "You've been kicked from the server for unlinking your discord account. Link again to join back!"
    discord-banned: "You have been banned on our discord server!"
    discord-banned-join: "You are unable to join because you have been banned on our discord server!"
  chat:
    prefix: "&#FF5555&lDiscordVerifier &#AA0000» &#FF5555"
    no-permission: "You don't have permission to execute this command."
    not-from-console: "You can't execute this command from console."
    info-command-usage: "Correct usage: &#FFFFFF/discord info <nickname>&#FF5555."
    player-not-verified: "Player is not verified."
    player-not-found: "Player cannot be found."
    player-info:
      - "&#FF5555Information about &#FFFFFF{}&#FF5555:"
      - "&#FF5555UUID: &#FFFFFF{}"
      - "&#FF5555Discord ID: &#FFFFFF{}"
      - "&#FF5555Discord Name: &#FFFFFF{}"
      - "&#FF5555Online: &#FFFFFF{}"
    discord-info: "Join our Discord server and get verified right now, if you haven't already: &#FFFFFFdiscord.gg/someserver&#FF5555."
    verification-request: "You received verification request from Discord account &#FFFFFF{}&#FF5555. To accept verification, type &#FFFFFF/discord accept&#FF5555, to deny it, type &#FFFFFF/discord deny&#FF5555."
    verification-expired: "Verification request from Discord account &#FFFFFF{} &#FF5555expired."
    verification-denied: "You denied verification request."
    verified-successfully: "Your Discord account has been verified and successfully linked with Discord account &#FFFFFF{}&#FF5555."
    no-requests: "You don't have any verification request."
    not-verified: "You are not verified."
    verification-canceled: "Successfully unlinked your account, you are not verified now."
    not-verified-yet: "Join our Discord server and get verified right now: &#FFFFFFdiscord.gg/someserver&#FF5555."
    config-reloaded: "Config has been reloaded."
    online-in-message: "online"
    offline-in-message: "offline"
  discord:
    player-not-found:
      title: "Player {} isn't on the server!"
      body: "Please join the server first to link your account. IP: play.awesomemcserver.com"
      footer: ""
    player-already-verified:
      title: "Player with username {} is already linked to a discord account."
      body: "If you want to undo your verification, use !mcunlink or /discord unlink in-game."
      footer: ""
    discord-already-verified:
      title: "Your Discord account is already linked to a minecraft account."
      body: "If you want to undo your verification, use /discord unlink command in-game."
      footer: ""
    verification-accepted:
      title: "Player {} has been found on the server."
      body: "You have to accept the verification, please type /discord accept in-game."
      footer: ""
    verification-denied:
      title: "Verification has been denied."
      body: "Player {} cancelled the verification in-game."
      footer: ""
    verification-success:
      title: "Verification was successful."
      body: "You are now verifed and your accounts are linked."
      footer: "If you want to unlink your account, type /discord unlink in-game."
    unlink-success:
      title: "Your account has been unlinked."
      body: "Use !mclink <mcusername> to link your account again."
      footer: ""